spring:
  application:
    name = cyber-news
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: ${JPA_DATABASE_PLATFORM}
    show-sql: true
  datasource:
    url: ${DATASOURCE_URL}
    username : ${DATASOURCE_USERNAME}
    password : ${DATASOURCE_PASSWORD}
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME}
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 5s
    socket-timeout: 30s
jwt:
  secretKey: ${SECRET_KEY}
cve:
  nist:
    url: ${NIST_CVE_URI}